### ISSUE TITLE
添加cookies后可以下载了，但是ws经常断流

### ISSUE THREAD

**Issue by supercell532** [auqhjjqdo/LiveRecorder#2]
2023-03-18 00:56:16.422 | INFO     | __main__:stream_writer:114 - 获取到直播流链接
[2023.03.18 00.56.14][twitcasting][θ 桃天ユエ ໒꒱]︎︎❤︎ 悪魔の心の診療所
wss://202-218-143-87.twitcasting.tv/ws.app/stream/762078263/fmp4/bd/1/1500?mode=main
Connection to remote host was lost.
2023-03-18 01:01:00.654 | ERROR    | __main__:stream_writer:125 - 文件写入错误
[2023.03.18 00.56.14][twitcasting][θ 桃天ユエ ໒꒱]︎︎❤︎ 悪魔の心の診療所
Read timeout
Traceback (most recent call last):

  File "threading.py", line 973, in _bootstrap

  File "threading.py", line 1016, in _bootstrap_inner

  File "threading.py", line 953, in run

  File "concurrent\futures\thread.py", line 83, in _worker

  File "concurrent\futures\thread.py", line 58, in run

> File "main.py", line 119, in stream_writer

  File "C:\Users\xing\AppData\Local\Temp\_MEI260362\streamlink\plugins\twitcasting.py", line 139, in read
    return self.buffer.read(
           │    │      └ <function RingBuffer.read at 0x0000021661756CB0>
           │    └ <streamlink.buffers.RingBuffer object at 0x0000021662D4E110>
           └ <streamlink.plugins.twitcasting.TwitCastingReader object at 0x0000021660CDA110>

  File "streamlink\buffers.py", line 109, in read

OSError: Read timeout

**Comment by supercell532** [comment]
twitcasting的ws老是断，根本用不了

**Comment by auqhjjqdo** [comment]
断流是代理丢包导致的吧，报错都是`Connection to remote host was lost.`网络错误，而且都是上游streamlink内部中断的，steamlink那边没看到issue说twitcasting的ws录制中断的问题
换一下梯子节点或者放国外服务器录制
