### ISSUE TITLE
[Bug]: 抖音录制报错：AttributeError("'NoneType' object has no attribute 'group'")

### ISSUE THREAD

**Issue by SingleRottenChips** [auqhjjqdo/LiveRecorder#29]
### 运行环境

版本号：2.18
运行平台：PC
运行架构：Windows 10
Python版本：3.3

### 配置文件

```JSON
{
  "proxy": null,
  "output": "output",
  "user": [
    {
	  "platform": "Douyin",
      "id": "xxxxxxxxxxx",
      "name": "xxxx",
	  "interval": 10,
      "format": "mp4",
      "headers": {
        "Referer": "https://live.douyin.com/"
      }
	}
  ]
}
```

### 复现步骤（可选）

1.
2.
3.
...

### 错误描述

见错误日志。

录制斗鱼、虎牙、B站都正常。

### 错误日志

[2023-07-18 14:48:01][INFO][__main__][start:47][Douyin][xxxxx]正在检测直播状态
[2023-07-18 14:48:04][ERROR][__main__][start:58][Douyin][xxxxxx]直播检测未知错误
AttributeError("'NoneType' object has no attribute 'group'")
Traceback (most recent call last):

  File "main.py", line 398, in <module>

  File "asyncio\runners.py", line 44, in run

  File "asyncio\base_events.py", line 636, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 603, in run_forever

  File "asyncio\base_events.py", line 1909, in _run_once

  File "asyncio\events.py", line 80, in _run

> File "main.py", line 50, in start

  File "main.py", line 259, in run

AttributeError: 'NoneType' object has no attribute 'group'

**Comment by auqhjjqdo** [comment]
方便提供一下主播id吗，我这边测试是正常的
![image](https://github.com/auqhjjqdo/LiveRecorder/assets/84632728/5adb6ebd-cb8c-48ac-8183-188be4a1c1fb)

**Comment by auqhjjqdo** [comment]
请将headers删除后再尝试，此字段非必填
