### ISSUE TITLE
[Bug]: 录制Twitcasting报错

### ISSUE THREAD

**Issue by supercell532** [auqhjjqdo/LiveRecorder#31]
### 运行环境

版本号：最新2.18
运行平台：win10
运行架构：
Python版本：

### 配置文件

```JSON
{

"format": "ts",
"interval": 5,
"user": [
{
"platform": "Twitcasting",
"format": "ts",
"id": "ym7ix",
"name": "θ 桃天ユエ ໒꒱"
}]
}
```

### 复现步骤（可选）

1.
2.
3.
...

### 错误描述

见日志

### 错误日志

[2023-07-20 22:01:33][ERROR][__main__][stream_writer:156][Twitcasting][θ 桃天ユエ ໒꒱]直播录制未知错误
No data returned from stream
Traceback (most recent call last):

  File "threading.py", line 973, in _bootstrap

  File "threading.py", line 1016, in _bootstrap_inner

  File "threading.py", line 953, in run

  File "concurrent\futures\thread.py", line 83, in _worker

  File "concurrent\futures\thread.py", line 58, in run

  File "main.py", line 133, in run_record

> File "main.py", line 146, in stream_writer

  File "streamlink_cli\main.py", line 320, in open_stream

streamlink.exceptions.StreamError: No data returned from stream
[2023-07-20 22:01:33][INFO][__main__][run_ffmpeg:161][Twitcasting][θ 桃天ユエ ໒꒱]开始ffmpeg封装：[2023.07.20 22.01.31][Twitcasting][θ 桃天ユエ ໒꒱]心が楽になるASMR🩹ྀི️マウサ2400.mp4
[2023-07-20 22:01:33][ERROR][__main__][start:57][Twitcasting][θ 桃天ユエ ໒꒱]直播检测未知错误
Error('ffmpeg error (see stderr output for detail)')
Traceback (most recent call last):

  File "main.py", line 397, in <module>

  File "asyncio\runners.py", line 44, in run

  File "asyncio\base_events.py", line 636, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 603, in run_forever

  File "asyncio\base_events.py", line 1909, in _run_once

  File "asyncio\events.py", line 80, in _run

> File "main.py", line 49, in start

  File "main.py", line 353, in run

  File "asyncio\threads.py", line 25, in to_thread

  File "concurrent\futures\thread.py", line 58, in run

  File "main.py", line 136, in run_record

  File "main.py", line 168, in run_ffmpeg

  File "ffmpeg\_run.py", line 325, in run

ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

**Comment by auqhjjqdo** [comment]
你确认主播已经开播了吗，这个是streamlink那边的报错，可能是没找到直播地址

**Comment by zhangmx999** [comment]
我觉得程序应该对没开播的情况，进行提示说明，而不应该抛出异常

**Comment by auqhjjqdo** [comment]
已尝试对异常捕获优化了提示，请下载v2.19版本测试是否正常出现提示

**Comment by zhangmx999** [comment]
点个赞
