### ISSUE TITLE
Twitcasting录制不了

### ISSUE THREAD

**Issue by supercell532** [auqhjjqdo/LiveRecorder#5]
`{
  "format": "mp4",
  "user": [
    {
      "platform": "Twitcasting",
      "id": "ym7ix",
      "name": "θ 桃天ユエ ໒꒱"
    }
  ]
}`

**Comment by supercell532** [comment]
[2023-04-17 23:23:53][ERROR][__main__][request:61][Twitcasting][θ 桃天ユエ ໒꒱]直播检测请求错误
HTTPStatusError("Client error '400 Bad Request' for url 'https://frontendapi.twitcasting.tv/users/ym7ix/latest-movie'\nFor more information check: https://httpstatuses.com/400")

**Comment by auqhjjqdo** [comment]
tc最近加密了api接口，已经逆向解密，晚点更新

**Comment by supercell532** [comment]
AttributeError("'NoneType' object has no attribute 'group'")
Traceback (most recent call last):

  File "main.py", line 320, in <module>

  File "asyncio\runners.py", line 44, in run

  File "asyncio\base_events.py", line 636, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 603, in run_forever

  File "asyncio\base_events.py", line 1909, in _run_once

  File "asyncio\events.py", line 80, in _run

> File "main.py", line 47, in start

  File "main.py", line 258, in run

AttributeError: 'NoneType' object has no attribute 'group'

**Comment by supercell532** [comment]
这是新的报错日志

**Comment by supercell532** [comment]
KeyError('title')
Traceback (most recent call last):

  File "main.py", line 320, in <module>

  File "asyncio\runners.py", line 44, in run

  File "asyncio\base_events.py", line 636, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 603, in run_forever

  File "asyncio\base_events.py", line 1909, in _run_once

  File "asyncio\events.py", line 80, in _run

> File "main.py", line 47, in start

  File "main.py", line 282, in run

KeyError: 'title'

**Comment by supercell532** [comment]
Twitcasting的录播又出问题了

**Comment by auqhjjqdo** [comment]
发一下哪个主播，我这儿随便测试的主播能录制

**Comment by supercell532** [comment]
好像未开播才会报这个错误

**Comment by auqhjjqdo** [comment]
未开播的主播我这儿测试也正常，这个报错是判定主播开播之后获取直播间标题失败导致的，可能是主播直播间的一些设置导致无法获取到，偶发bug不好处理

**Comment by supercell532** [comment]
[2023-05-01 13:31:32][ERROR][__main__][start:50][Twitcasting][θ 桃天ユエ ໒꒱]直播检测未知错误
TypeError("unhashable type: 'bytearray'")
Traceback (most recent call last):

  File "main.py", line 323, in <module>

  File "asyncio\runners.py", line 44, in run

  File "asyncio\base_events.py", line 636, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 603, in run_forever

  File "asyncio\base_events.py", line 1909, in _run_once

  File "asyncio\events.py", line 80, in _run

> File "main.py", line 46, in start

  File "main.py", line 279, in run

  File "main.py", line 58, in request

  File "httpx\_client.py", line 1530, in request

  File "httpx\_client.py", line 1617, in send

  File "httpx\_client.py", line 1645, in _send_handling_auth

  File "httpx\_client.py", line 1682, in _send_handling_redirects

  File "httpx\_client.py", line 1719, in _send_single_request

  File "httpx\_transports\default.py", line 353, in handle_async_request

  File "httpcore\_async\connection_pool.py", line 253, in handle_async_request

  File "httpcore\_async\connection_pool.py", line 237, in handle_async_request

  File "httpcore\_async\socks_proxy.py", line 292, in handle_async_request

  File "httpcore\_async\socks_proxy.py", line 240, in handle_async_request

  File "httpcore\_async\socks_proxy.py", line 93, in _init_socks5_connection

  File "socksio\socks5.py", line 382, in receive_data

  File "socksio\socks5.py", line 262, in loads

**Comment by supercell532** [comment]
很抱歉五一打扰，这是新的报错日志

**Comment by auqhjjqdo** [comment]
上游socks5代理的bug导致的，改用http代理或尝试新版本

**Comment by supercell532** [comment]
:-)

**Comment by supercell532** [comment]
还有个问题，录播格式设置成ts之后。 录播文件被切的很碎，每8-10Mb就会重新开启ffmpeg管道

**Comment by auqhjjqdo** [comment]
![image](https://user-images.githubusercontent.com/84632728/235586950-cdf6fba4-db9e-4cb6-921e-e962a6310500.png)
实测ts格式无问题，被切碎可能是代理丢包导致的读取直播流超时，然后就自动重新录制了
