### ISSUE TITLE
抖音直播录制出现错误，[Bug]: 

### ISSUE THREAD

**Issue by 0zxcvbnm0** [auqhjjqdo/LiveRecorder#57]
### 运行环境

版本号：最新
运行平台：Windows
运行架构：64
Python版本：
3.8.2

### 配置文件

```JSON
{
  "proxy": "http://127.0.0.1:7890",
  "output": "output",
  "user": [
{
"platform": "Douyin",
"id": "165815135695",
"name": "露宝888"
},
{
"platform": "Douyin",
"id": "107940031377",
"name": "二嫂"
},
{
"platform": "Douyin",
"id": "881915323288",
"name": "冯提莫"
    }
  ]
```

### 复现步骤（可选）

1.
2.
3.
...

### 错误描述

pdd直播检测错误
远程计算机拒绝连接

### 错误日志

```Text
[2023-11-01 16:53:46][INFO][__main__][start:47][Pandalive][seeenv]正在检测直播状态
[2023-11-01 16:53:48][ERROR][__main__][start:58][Douyin][央视新闻]直播检测错误
ProxyConnectionError(None, 'Could not connect to proxy 127.0.0.1:7890 [None]')
Traceback (most recent call last):

  File "anyio\_core\_sockets.py", line 168, in try_connect

  File "anyio\_backends\_asyncio.py", line 2202, in connect_tcp

  File "asyncio\base_events.py", line 1076, in create_connection

  File "asyncio\base_events.py", line 1060, in create_connection

  File "asyncio\base_events.py", line 969, in _connect_sock

  File "asyncio\proactor_events.py", line 709, in sock_connect

  File "asyncio\windows_events.py", line 826, in _poll

  File "asyncio\windows_events.py", line 613, in finish_connect

ConnectionRefusedError: [WinError 1225] 远程计算机拒绝网络连接。


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "python_socks\async_\anyio\_proxy.py", line 59, in connect

  File "python_socks\async_\anyio\_connect.py", line 11, in connect_tcp

  File "anyio\_core\_sockets.py", line 230, in connect_tcp

OSError: All connection attempts failed
```

**Comment by auqhjjqdo** [comment]
请仔细阅读readme，需要代理时才填
