### ISSUE TITLE
正在直播却不录制

### ISSUE THREAD

**Issue by lhs55502002** [auqhjjqdo/LiveRecorder#63]
### 运行环境

版本号：v2.27
运行平台：windows11
运行架构：64
Python版本：3.11

### 配置文件

```JSON
{
  "proxy": "http://127.0.0.1:7890",
  "output": "E:/L",
  "user": [
    {
      "platform": "Twitch",
      "id": "frivvifox",
      "name": "FrivviFox"
    },
    {
      "platform": "Youtube",
      "id": "UCzk5x_PbhFKUoJx_HNTefDQ",
      "name": "111111",
      "headers": {
        "Referer": "https://www.youtube.com/"
      },
      "cookies": ""
    },
```

### 复现步骤（可选）

1.打开liverecord
2.错误出现
...

### 错误描述

明明 在直播，却没录制

### 错误日志

```Text
[2023-11-23 00:41:34][INFO][__main__][start:47][Twitch][FrivviFox]正在检测直播状态
[2023-11-23 00:41:34][INFO][__main__][start:47][Youtube][Sleepy Beauty ASMR]正在检测直播状态
[2023-11-23 00:41:34][INFO][__main__][start:47][Youtube][FrivolousFox ASMR]正在检测直播状态
[2023-11-23 00:41:34][INFO][__main__][start:47][Youtube][Cute KR]正在检测直播状态
[2023-11-23 00:41:34][INFO][__main__][start:47][Youtube][Miss Ruby's World]正在检测直播状态
[2023-11-23 00:41:34][INFO][__main__][start:47][Youtube][Asian Babe ASMR]正在检测直播状态
[2023-11-23 00:45:42][INFO][__main__][start:47][Twitch][FrivviFox]正在检测直播状态
[2023-11-23 00:45:42][INFO][__main__][start:47][Youtube][111111]正在检测直播状态
[2023-11-23 00:45:42][INFO][__main__][start:47][Youtube][Sleepy Beauty ASMR]正在检测直播状态
[2023-11-23 00:45:42][INFO][__main__][start:47][Youtube][FrivolousFox ASMR]正在检测直播状态
[2023-11-23 00:45:42][INFO][__main__][start:47][Youtube][Cute KR]正在检测直播状态
[2023-11-23 00:45:42][INFO][__main__][start:47][Youtube][Miss Ruby's World]正在检测直播状态
[2023-11-23 00:45:42][INFO][__main__][start:47][Youtube][Asian Babe ASMR]正在检测直播状态
[2023-11-23 00:47:51][INFO][__main__][start:47][Twitch][FrivviFox]正在检测直播状态
[2023-11-23 00:47:51][INFO][__main__][start:47][Youtube][111111]正在检测直播状态
[2023-11-23 00:47:51][INFO][__main__][start:47][Youtube][Sleepy Beauty ASMR]正在检测直播状态
[2023-11-23 00:47:51][INFO][__main__][start:47][Youtube][FrivolousFox ASMR]正在检测直播状态
[2023-11-23 00:47:51][INFO][__main__][start:47][Youtube][Cute KR]正在检测直播状态
[2023-11-23 00:47:51][INFO][__main__][start:47][Youtube][Miss Ruby's World]正在检测直播状态
[2023-11-23 00:47:51][INFO][__main__][start:47][Youtube][Asian Babe ASMR]正在检测直播状态
[2023-11-23 00:47:57][ERROR][__main__][start:58][Youtube][111111]直播检测错误
AttributeError("'str' object has no attribute 'extract_cookies'")
Traceback (most recent call last):

  File "live_recorder.py", line 468, in <module>

  File "asyncio\runners.py", line 44, in run

  File "asyncio\base_events.py", line 636, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 603, in run_forever

  File "asyncio\base_events.py", line 1909, in _run_once

  File "asyncio\events.py", line 80, in _run

> File "live_recorder.py", line 50, in start

  File "live_recorder.py", line 286, in run

  File "tenacity\_asyncio.py", line 88, in async_wrapped

  File "tenacity\_asyncio.py", line 47, in __call__

  File "tenacity\__init__.py", line 325, in iter

  File "tenacity\__init__.py", line 158, in reraise

  File "concurrent\futures\_base.py", line 451, in result

  File "concurrent\futures\_base.py", line 403, in __get_result

  File "tenacity\_asyncio.py", line 50, in __call__

  File "live_recorder.py", line 66, in request

  File "httpx\_client.py", line 1530, in request

  File "httpx\_client.py", line 1617, in send

  File "httpx\_client.py", line 1645, in _send_handling_auth

  File "httpx\_client.py", line 1682, in _send_handling_redirects

  File "httpx\_client.py", line 1726, in _send_single_request

  File "httpx\_models.py", line 1038, in extract_cookies

AttributeError: 'str' object has no attribute 'extract_cookies'
[2023-11-23 00:48:00][ERROR][__main__][start:58][Youtube][111111]直播检测错误
AttributeError("'str' object has no attribute 'extract_cookies'")
Traceback (most recent call last):

  File "live_recorder.py", line 468, in <module>

  File "asyncio\runners.py", line 44, in run

  File "asyncio\base_events.py", line 636, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 603, in run_forever

  File "asyncio\base_events.py", line 1909, in _run_once

  File "asyncio\events.py", line 80, in _run

> File "live_recorder.py", line 50, in start

  File "live_recorder.py", line 286, in run

  File "tenacity\_asyncio.py", line 88, in async_wrapped

  File "tenacity\_asyncio.py", line 47, in __call__

  File "tenacity\__init__.py", line 325, in iter

  File "tenacity\__init__.py", line 158, in reraise

  File "concurrent\futures\_base.py", line 451, in result

  File "concurrent\futures\_base.py", line 403, in __get_result

  File "tenacity\_asyncio.py", line 50, in __call__

  File "live_recorder.py", line 66, in request

  File "httpx\_client.py", line 1530, in request

  File "httpx\_client.py", line 1617, in send

  File "httpx\_client.py", line 1645, in _send_handling_auth

  File "httpx\_client.py", line 1682, in _send_handling_redirects

  File "httpx\_client.py", line 1726, in _send_single_request

  File "httpx\_models.py", line 1038, in extract_cookies

AttributeError: 'str' object has no attribute 'extract_cookies'
[2023-11-23 00:48:02][ERROR][__main__][start:58][Youtube][111111]直播检测错误
AttributeError("'str' object has no attribute 'extract_cookies'")
Traceback (most recent call last):

  File "live_recorder.py", line 468, in <module>

  File "asyncio\runners.py", line 44, in run

  File "asyncio\base_events.py", line 636, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 603, in run_forever

  File "asyncio\base_events.py", line 1909, in _run_once

  File "asyncio\events.py", line 80, in _run

> File "live_recorder.py", line 50, in start

  File "live_recorder.py", line 286, in run

  File "tenacity\_asyncio.py", line 88, in async_wrapped

  File "tenacity\_asyncio.py", line 47, in __call__

  File "tenacity\__init__.py", line 325, in iter

  File "tenacity\__init__.py", line 158, in reraise

  File "concurrent\futures\_base.py", line 451, in result

  File "concurrent\futures\_base.py", line 403, in __get_result

  File "tenacity\_asyncio.py", line 50, in __call__

  File "live_recorder.py", line 66, in request

  File "httpx\_client.py", line 1530, in request

  File "httpx\_client.py", line 1617, in send

  File "httpx\_client.py", line 1645, in _send_handling_auth

  File "httpx\_client.py", line 1682, in _send_handling_redirects

  File "httpx\_client.py", line 1726, in _send_single_request

  File "httpx\_models.py", line 1038, in extract_cookies

AttributeError: 'str' object has no attribute 'extract_cookies'
[2023-11-23 00:48:04][ERROR][__main__][start:58][Youtube][111111]直播检测错误
AttributeError("'str' object has no attribute 'extract_cookies'")
Traceback (most recent call last):

  File "live_recorder.py", line 468, in <module>

  File "asyncio\runners.py", line 44, in run

  File "asyncio\base_events.py", line 636, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 603, in run_forever

  File "asyncio\base_events.py", line 1909, in _run_once

  File "asyncio\events.py", line 80, in _run

> File "live_recorder.py", line 50, in start

  File "live_recorder.py", line 286, in run

  File "tenacity\_asyncio.py", line 88, in async_wrapped

  File "tenacity\_asyncio.py", line 47, in __call__

  File "tenacity\__init__.py", line 325, in iter

  File "tenacity\__init__.py", line 158, in reraise

  File "concurrent\futures\_base.py", line 451, in result

  File "concurrent\futures\_base.py", line 403, in __get_result

  File "tenacity\_asyncio.py", line 50, in __call__

  File "live_recorder.py", line 66, in request

  File "httpx\_client.py", line 1530, in request

  File "httpx\_client.py", line 1617, in send

  File "httpx\_client.py", line 1645, in _send_handling_auth

  File "httpx\_client.py", line 1682, in _send_handling_redirects

  File "httpx\_client.py", line 1726, in _send_single_request

  File "httpx\_models.py", line 1038, in extract_cookies

AttributeError: 'str' object has no attribute 'extract_cookies'
[2023-11-23 00:48:06][ERROR][__main__][start:58][Youtube][111111]直播检测错误
AttributeError("'str' object has no attribute 'extract_cookies'")
Traceback (most recent call last):

  File "live_recorder.py", line 468, in <module>

  File "asyncio\runners.py", line 44, in run

  File "asyncio\base_events.py", line 636, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 603, in run_forever

  File "asyncio\base_events.py", line 1909, in _run_once

  File "asyncio\events.py", line 80, in _run

> File "live_recorder.py", line 50, in start

  File "live_recorder.py", line 286, in run

  File "tenacity\_asyncio.py", line 88, in async_wrapped

  File "tenacity\_asyncio.py", line 47, in __call__

  File "tenacity\__init__.py", line 325, in iter

  File "tenacity\__init__.py", line 158, in reraise

  File "concurrent\futures\_base.py", line 451, in result

  File "concurrent\futures\_base.py", line 403, in __get_result

  File "tenacity\_asyncio.py", line 50, in __call__

  File "live_recorder.py", line 66, in request

  File "httpx\_client.py", line 1530, in request

  File "httpx\_client.py", line 1617, in send

  File "httpx\_client.py", line 1645, in _send_handling_auth

  File "httpx\_client.py", line 1682, in _send_handling_redirects

  File "httpx\_client.py", line 1726, in _send_single_request

  File "httpx\_models.py", line 1038, in extract_cookies

AttributeError: 'str' object has no attribute 'extract_cookies'
[2023-11-23 00:48:08][ERROR][__main__][start:58][Youtube][111111]直播检测错误
AttributeError("'str' object has no attribute 'extract_cookies'")
Traceback (most recent call last):

  File "live_recorder.py", line 468, in <module>

  File "asyncio\runners.py", line 44, in run

  File "asyncio\base_events.py", line 636, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 603, in run_forever

  File "asyncio\base_events.py", line 1909, in _run_once

  File "asyncio\events.py", line 80, in _run

> File "live_recorder.py", line 50, in start

  File "live_recorder.py", line 286, in run

  File "tenacity\_asyncio.py", line 88, in async_wrapped

  File "tenacity\_asyncio.py", line 47, in __call__

  File "tenacity\__init__.py", line 325, in iter

  File "tenacity\__init__.py", line 158, in reraise

  File "concurrent\futures\_base.py", line 451, in result

  File "concurrent\futures\_base.py", line 403, in __get_result

  File "tenacity\_asyncio.py", line 50, in __call__

  File "live_recorder.py", line 66, in request

  File "httpx\_client.py", line 1530, in request

  File "httpx\_client.py", line 1617, in send

  File "httpx\_client.py", line 1645, in _send_handling_auth

  File "httpx\_client.py", line 1682, in _send_handling_redirects

  File "httpx\_client.py", line 1726, in _send_single_request

  File "httpx\_models.py", line 1038, in extract_cookies

AttributeError: 'str' object has no attribute 'extract_cookies'
[2023-11-23 00:48:10][ERROR][__main__][start:58][Youtube][111111]直播检测错误
AttributeError("'str' object has no attribute 'extract_cookies'")
Traceback (most recent call last):

  File "live_recorder.py", line 468, in <module>

  File "asyncio\runners.py", line 44, in run

  File "asyncio\base_events.py", line 636, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 603, in run_forever

  File "asyncio\base_events.py", line 1909, in _run_once

  File "asyncio\events.py", line 80, in _run

> File "live_recorder.py", line 50, in start

  File "live_recorder.py", line 286, in run

  File "tenacity\_asyncio.py", line 88, in async_wrapped

  File "tenacity\_asyncio.py", line 47, in __call__

  File "tenacity\__init__.py", line 325, in iter

  File "tenacity\__init__.py", line 158, in reraise

  File "concurrent\futures\_base.py", line 451, in result

  File "concurrent\futures\_base.py", line 403, in __get_result

  File "tenacity\_asyncio.py", line 50, in __call__

  File "live_recorder.py", line 66, in request

  File "httpx\_client.py", line 1530, in request

  File "httpx\_client.py", line 1617, in send

  File "httpx\_client.py", line 1645, in _send_handling_auth

  File "httpx\_client.py", line 1682, in _send_handling_redirects

  File "httpx\_client.py", line 1726, in _send_single_request

  File "httpx\_models.py", line 1038, in extract_cookies

AttributeError: 'str' object has no attribute 'extract_cookies'
[2023-11-23 00:48:14][ERROR][__main__][start:58][Youtube][111111]直播检测错误
AttributeError("'str' object has no attribute 'extract_cookies'")
Traceback (most recent call last):

  File "live_recorder.py", line 468, in <module>

  File "asyncio\runners.py", line 44, in run

  File "asyncio\base_events.py", line 636, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 603, in run_forever

  File "asyncio\base_events.py", line 1909, in _run_once

  File "asyncio\events.py", line 80, in _run

> File "live_recorder.py", line 50, in start

  File "live_recorder.py", line 286, in run

  File "tenacity\_asyncio.py", line 88, in async_wrapped

  File "tenacity\_asyncio.py", line 47, in __call__

  File "tenacity\__init__.py", line 325, in iter

  File "tenacity\__init__.py", line 158, in reraise

  File "concurrent\futures\_base.py", line 451, in result

  File "concurrent\futures\_base.py", line 403, in __get_result

  File "tenacity\_asyncio.py", line 50, in __call__

  File "live_recorder.py", line 66, in request

  File "httpx\_client.py", line 1530, in request

  File "httpx\_client.py", line 1617, in send

  File "httpx\_client.py", line 1645, in _send_handling_auth

  File "httpx\_client.py", line 1682, in _send_handling_redirects

  File "httpx\_client.py", line 1726, in _send_single_request

  File "httpx\_models.py", line 1038, in extract_cookies

AttributeError: 'str' object has no attribute 'extract_cookies'
[2023-11-23 00:48:15][ERROR][__main__][start:58][Youtube][111111]直播检测错误
AttributeError("'str' object has no attribute 'extract_cookies'")
Traceback (most recent call last):

  File "live_recorder.py", line 468, in <module>

  File "asyncio\runners.py", line 44, in run

  File "asyncio\base_events.py", line 636, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 603, in run_forever

  File "asyncio\base_events.py", line 1909, in _run_once

  File "asyncio\events.py", line 80, in _run

> File "live_recorder.py", line 50, in start

  File "live_recorder.py", line 286, in run

  File "tenacity\_asyncio.py", line 88, in async_wrapped

  File "tenacity\_asyncio.py", line 47, in __call__

  File "tenacity\__init__.py", line 325, in iter

  File "tenacity\__init__.py", line 158, in reraise

  File "concurrent\futures\_base.py", line 451, in result

  File "concurrent\futures\_base.py", line 403, in __get_result

  File "tenacity\_asyncio.py", line 50, in __call__

  File "live_recorder.py", line 66, in request

  File "httpx\_client.py", line 1530, in request

  File "httpx\_client.py", line 1617, in send

  File "httpx\_client.py", line 1645, in _send_handling_auth

  File "httpx\_client.py", line 1682, in _send_handling_redirects

  File "httpx\_client.py", line 1726, in _send_single_request

  File "httpx\_models.py", line 1038, in extract_cookies

AttributeError: 'str' object has no attribute 'extract_cookies'
[2023-11-23 00:48:17][ERROR][__main__][start:58][Youtube][111111]直播检测错误
AttributeError("'str' object has no attribute 'extract_cookies'")
Traceback (most recent call last):

  File "live_recorder.py", line 468, in <module>

  File "asyncio\runners.py", line 44, in run

  File "asyncio\base_events.py", line 636, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 603, in run_forever

  File "asyncio\base_events.py", line 1909, in _run_once

  File "asyncio\events.py", line 80, in _run

> File "live_recorder.py", line 50, in start

  File "live_recorder.py", line 286, in run

  File "tenacity\_asyncio.py", line 88, in async_wrapped

  File "tenacity\_asyncio.py", line 47, in __call__

  File "tenacity\__init__.py", line 325, in iter

  File "tenacity\__init__.py", line 158, in reraise

  File "concurrent\futures\_base.py", line 451, in result

  File "concurrent\futures\_base.py", line 403, in __get_result

  File "tenacity\_asyncio.py", line 50, in __call__

  File "live_recorder.py", line 66, in request

  File "httpx\_client.py", line 1530, in request

  File "httpx\_client.py", line 1617, in send

  File "httpx\_client.py", line 1645, in _send_handling_auth

  File "httpx\_client.py", line 1682, in _send_handling_redirects

  File "httpx\_client.py", line 1726, in _send_single_request

  File "httpx\_models.py", line 1038, in extract_cookies

AttributeError: 'str' object has no attribute 'extract_cookies'
[2023-11-23 00:48:19][ERROR][__main__][start:58][Youtube][111111]直播检测错误
AttributeError("'str' object has no attribute 'extract_cookies'")
Traceback (most recent call last):

  File "live_recorder.py", line 468, in <module>

  File "asyncio\runners.py", line 44, in run

  File "asyncio\base_events.py", line 636, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 603, in run_forever

  File "asyncio\base_events.py", line 1909, in _run_once

  File "asyncio\events.py", line 80, in _run

> File "live_recorder.py", line 50, in start

  File "live_recorder.py", line 286, in run

  File "tenacity\_asyncio.py", line 88, in async_wrapped

  File "tenacity\_asyncio.py", line 47, in __call__

  File "tenacity\__init__.py", line 325, in iter

  File "tenacity\__init__.py", line 158, in reraise

  File "concurrent\futures\_base.py", line 451, in result

  File "concurrent\futures\_base.py", line 403, in __get_result

  File "tenacity\_asyncio.py", line 50, in __call__

  File "live_recorder.py", line 66, in request

  File "httpx\_client.py", line 1530, in request

  File "httpx\_client.py", line 1617, in send

  File "httpx\_client.py", line 1645, in _send_handling_auth

  File "httpx\_client.py", line 1682, in _send_handling_redirects

  File "httpx\_client.py", line 1726, in _send_single_request

  File "httpx\_models.py", line 1038, in extract_cookies

AttributeError: 'str' object has no attribute 'extract_cookies'
[2023-11-23 00:48:21][ERROR][__main__][start:58][Youtube][111111]直播检测错误
AttributeError("'str' object has no attribute 'extract_cookies'")
Traceback (most recent call last):

  File "live_recorder.py", line 468, in <module>

  File "asyncio\runners.py", line 44, in run

  File "asyncio\base_events.py", line 636, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 603, in run_forever

  File "asyncio\base_events.py", line 1909, in _run_once

  File "asyncio\events.py", line 80, in _run

> File "live_recorder.py", line 50, in start

  File "live_recorder.py", line 286, in run

  File "tenacity\_asyncio.py", line 88, in async_wrapped

  File "tenacity\_asyncio.py", line 47, in __call__

  File "tenacity\__init__.py", line 325, in iter

  File "tenacity\__init__.py", line 158, in reraise

  File "concurrent\futures\_base.py", line 451, in result

  File "concurrent\futures\_base.py", line 403, in __get_result

  File "tenacity\_asyncio.py", line 50, in __call__

  File "live_recorder.py", line 66, in request

  File "httpx\_client.py", line 1530, in request

  File "httpx\_client.py", line 1617, in send

  File "httpx\_client.py", line 1645, in _send_handling_auth

  File "httpx\_client.py", line 1682, in _send_handling_redirects

  File "httpx\_client.py", line 1726, in _send_single_request

  File "httpx\_models.py", line 1038, in extract_cookies

AttributeError: 'str' object has no attribute 'extract_cookies'
[2023-11-23 00:48:22][ERROR][__main__][start:58][Youtube][111111]直播检测错误
AttributeError("'str' object has no attribute 'extract_cookies'")
Traceback (most recent call last):

  File "live_recorder.py", line 468, in <module>

  File "asyncio\runners.py", line 44, in run

  File "asyncio\base_events.py", line 636, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 603, in run_forever

  File "asyncio\base_events.py", line 1909, in _run_once

  File "asyncio\events.py", line 80, in _run

> File "live_recorder.py", line 50, in start

  File "live_recorder.py", line 286, in run

  File "tenacity\_asyncio.py", line 88, in async_wrapped

  File "tenacity\_asyncio.py", line 47, in __call__

  File "tenacity\__init__.py", line 325, in iter

  File "tenacity\__init__.py", line 158, in reraise

  File "concurrent\futures\_base.py", line 451, in result

  File "concurrent\futures\_base.py", line 403, in __get_result

  File "tenacity\_asyncio.py", line 50, in __call__

  File "live_recorder.py", line 66, in request

  File "httpx\_client.py", line 1530, in request

  File "httpx\_client.py", line 1617, in send

  File "httpx\_client.py", line 1645, in _send_handling_auth

  File "httpx\_client.py", line 1682, in _send_handling_redirects

  File "httpx\_client.py", line 1726, in _send_single_request

  File "httpx\_models.py", line 1038, in extract_cookies

AttributeError: 'str' object has no attribute 'extract_cookies'
[2023-11-23 00:48:24][ERROR][__main__][start:58][Youtube][111111]直播检测错误
AttributeError("'str' object has no attribute 'extract_cookies'")
Traceback (most recent call last):

  File "live_recorder.py", line 468, in <module>

  File "asyncio\runners.py", line 44, in run

  File "asyncio\base_events.py", line 636, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 603, in run_forever

  File "asyncio\base_events.py", line 1909, in _run_once

  File "asyncio\events.py", line 80, in _run

> File "live_recorder.py", line 50, in start

  File "live_recorder.py", line 286, in run

  File "tenacity\_asyncio.py", line 88, in async_wrapped

  File "tenacity\_asyncio.py", line 47, in __call__

  File "tenacity\__init__.py", line 325, in iter

  File "tenacity\__init__.py", line 158, in reraise

  File "concurrent\futures\_base.py", line 451, in result

  File "concurrent\futures\_base.py", line 403, in __get_result

  File "tenacity\_asyncio.py", line 50, in __call__

  File "live_recorder.py", line 66, in request

  File "httpx\_client.py", line 1530, in request

  File "httpx\_client.py", line 1617, in send

  File "httpx\_client.py", line 1645, in _send_handling_auth

  File "httpx\_client.py", line 1682, in _send_handling_redirects

  File "httpx\_client.py", line 1726, in _send_single_request

  File "httpx\_models.py", line 1038, in extract_cookies

AttributeError: 'str' object has no attribute 'extract_cookies'
[2023-11-23 00:48:26][ERROR][__main__][start:58][Youtube][111111]直播检测错误
AttributeError("'str' object has no attribute 'extract_cookies'")
Traceback (most recent call last):

  File "live_recorder.py", line 468, in <module>

  File "asyncio\runners.py", line 44, in run

  File "asyncio\base_events.py", line 636, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 603, in run_forever

  File "asyncio\base_events.py", line 1909, in _run_once

  File "asyncio\events.py", line 80, in _run

> File "live_recorder.py", line 50, in start

  File "live_recorder.py", line 286, in run

  File "tenacity\_asyncio.py", line 88, in async_wrapped

  File "tenacity\_asyncio.py", line 47, in __call__

  File "tenacity\__init__.py", line 325, in iter

  File "tenacity\__init__.py", line 158, in reraise

  File "concurrent\futures\_base.py", line 451, in result

  File "concurrent\futures\_base.py", line 403, in __get_result

  File "tenacity\_asyncio.py", line 50, in __call__

  File "live_recorder.py", line 66, in request

  File "httpx\_client.py", line 1530, in request

  File "httpx\_client.py", line 1617, in send

  File "httpx\_client.py", line 1645, in _send_handling_auth

  File "httpx\_client.py", line 1682, in _send_handling_redirects

  File "httpx\_client.py", line 1726, in _send_single_request

  File "httpx\_models.py", line 1038, in extract_cookies

AttributeError: 'str' object has no attribute 'extract_cookies'
[2023-11-23 00:48:28][ERROR][__main__][start:58][Youtube][111111]直播检测错误
AttributeError("'str' object has no attribute 'extract_cookies'")
Traceback (most recent call last):

  File "live_recorder.py", line 468, in <module>

  File "asyncio\runners.py", line 44, in run

  File "asyncio\base_events.py", line 636, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 603, in run_forever

  File "asyncio\base_events.py", line 1909, in _run_once

  File "asyncio\events.py", line 80, in _run

> File "live_recorder.py", line 50, in start

  File "live_recorder.py", line 286, in run

  File "tenacity\_asyncio.py", line 88, in async_wrapped

  File "tenacity\_asyncio.py", line 47, in __call__

  File "tenacity\__init__.py", line 325, in iter

  File "tenacity\__init__.py", line 158, in reraise

  File "concurrent\futures\_base.py", line 451, in result

  File "concurrent\futures\_base.py", line 403, in __get_result

  File "tenacity\_asyncio.py", line 50, in __call__

  File "live_recorder.py", line 66, in request

  File "httpx\_client.py", line 1530, in request

  File "httpx\_client.py", line 1617, in send

  File "httpx\_client.py", line 1645, in _send_handling_auth

  File "httpx\_client.py", line 1682, in _send_handling_redirects

  File "httpx\_client.py", line 1726, in _send_single_request

  File "httpx\_models.py", line 1038, in extract_cookies

AttributeError: 'str' object has no attribute 'extract_cookies'
[2023-11-23 00:48:30][ERROR][__main__][start:58][Youtube][111111]直播检测错误
AttributeError("'str' object has no attribute 'extract_cookies'")
Traceback (most recent call last):

  File "live_recorder.py", line 468, in <module>

  File "asyncio\runners.py", line 44, in run

  File "asyncio\base_events.py", line 636, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 603, in run_forever

  File "asyncio\base_events.py", line 1909, in _run_once

  File "asyncio\events.py", line 80, in _run

> File "live_recorder.py", line 50, in start

  File "live_recorder.py", line 286, in run

  File "tenacity\_asyncio.py", line 88, in async_wrapped

  File "tenacity\_asyncio.py", line 47, in __call__

  File "tenacity\__init__.py", line 325, in iter

  File "tenacity\__init__.py", line 158, in reraise

  File "concurrent\futures\_base.py", line 451, in result

  File "concurrent\futures\_base.py", line 403, in __get_result

  File "tenacity\_asyncio.py", line 50, in __call__

  File "live_recorder.py", line 66, in request

  File "httpx\_client.py", line 1530, in request

  File "httpx\_client.py", line 1617, in send

  File "httpx\_client.py", line 1645, in _send_handling_auth

  File "httpx\_client.py", line 1682, in _send_handling_redirects

  File "httpx\_client.py", line 1726, in _send_single_request

  File "httpx\_models.py", line 1038, in extract_cookies

AttributeError: 'str' object has no attribute 'extract_cookies'
[2023-11-23 00:48:30][INFO][__main__][start:47][Twitch][FrivviFox]正在检测直播状态
[2023-11-23 00:48:30][INFO][__main__][start:47][Youtube][111111]正在检测直播状态
[2023-11-23 00:48:30][INFO][__main__][start:47][Youtube][Sleepy Beauty ASMR]正在检测直播状态
[2023-11-23 00:48:30][INFO][__main__][start:47][Youtube][FrivolousFox ASMR]正在检测直播状态
[2023-11-23 00:48:30][INFO][__main__][start:47][Youtube][Cute KR]正在检测直播状态
[2023-11-23 00:48:30][INFO][__main__][start:47][Youtube][Miss Ruby's World]正在检测直播状态
[2023-11-23 00:48:30][INFO][__main__][start:47][Youtube][Asian Babe ASMR]正在检测直播状态
```

**Comment by auqhjjqdo** [comment]
在无需登录就能观看直播请不要填写cookies

**Comment by lhs55502002** [comment]
> 在无需登录就能观看直播请不要填写cookies

刚删了cookies也 不行，不光youtube,twitch也是直播不录制，大佬你可以试试

**Comment by lhs55502002** [comment]
今天试了下twitch能录。不知道为什么

**Comment by auqhjjqdo** [comment]
twitch获取到直播链接后会等十几秒的广告时间，随后才会正常开始录制，这是twitch直播源限制
youtube我看了下是接口有更新，稍后发新版
