### ISSUE TITLE
斗鱼录制不了，前天还能录制，今天就开始报错了，测试了虎牙可以录制但是斗鱼录不了

### ISSUE THREAD

**Issue by tansaox2008123** [auqhjjqdo/LiveRecorder#68]
### 运行环境

版本号：2.29
运行平台：windows
运行架构：x64
Python版本：3.8

### 配置文件

```JSON
{
  "output": "D:/vidio/jg",
  "user": [
    {
      "platform": "Douyu",
      "id": "242737",
      "name": "Ori曾焦阳",
      "interval": 10,
      "format": "mp4"
    }
  ]
}
```

### 复现步骤（可选）

1.
2.
3.
...

### 错误描述

jsengine.exceptions.ProgramError: ReferenceError: 'window' is not defined
    at send (<input>)
    at <eval> (<input>:1)

### 错误日志

```Text
[2023-12-13 10:40:38][INFO][__main__][run_record:139][Douyu][Ori曾焦阳]停止录制：[2023.12.13 10.35.15][Douyu][Ori曾焦阳]上班了！242737.flv
[2023-12-13 10:40:49][ERROR][__main__][start:58][Douyu][Ori曾焦阳]直播检测错误
ProgramError("ReferenceError: 'window' is not defined\n    at send (<input>)\n    at <eval> (<input>:1)\n")
Traceback (most recent call last):

  File "jsengine\internal.py", line 145, in eval

_quickjs.JSException: ReferenceError: 'window' is not defined
    at send (<input>)
    at <eval> (<input>:1)



During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "live_recorder.py", line 467, in <module>

  File "asyncio\runners.py", line 44, in run

  File "asyncio\base_events.py", line 636, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 603, in run_forever

  File "asyncio\base_events.py", line 1909, in _run_once

  File "asyncio\events.py", line 80, in _run

> File "live_recorder.py", line 50, in start

  File "live_recorder.py", line 202, in run

  File "live_recorder.py", line 228, in get_live

  File "jsengine\util.py", line 75, in newfunc

  File "<string>", line 16, in call

  File "jsengine\util.py", line 75, in newfunc

  File "jsengine\abstract.py", line 89, in eval

  File "jsengine\abstract.py", line 77, in _append_stand_source

  File "jsengine\internal.py", line 17, in _append

  File "jsengine\internal.py", line 147, in eval

jsengine.exceptions.ProgramError: ReferenceError: 'window' is not defined
    at send (<input>)
    at <eval> (<input>:1)

[2023-12-13 10:40:50][ERROR][__main__][start:58][Douyu][Ori曾焦阳]直播检测错误
ProgramError("ReferenceError: 'window' is not defined\n    at send (<input>)\n    at <eval> (<input>:1)\n")
Traceback (most recent call last):

  File "jsengine\internal.py", line 145, in eval

_quickjs.JSException: ReferenceError: 'window' is not defined
    at send (<input>)
    at <eval> (<input>:1)
```

**Comment by auqhjjqdo** [comment]
![image](https://github.com/auqhjjqdo/LiveRecorder/assets/84632728/24722551-cfbd-4a7b-8b69-09805e403bc4)
我这边测试能录制啊

**Comment by tansaox2008123** [comment]
谢谢啦，我这里也可以正常录制了，不知道那天出了啥问题，再次感谢&nbsp;


卖火柴的小菇凉?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月16日(星期六) 晚上9:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [auqhjjqdo/LiveRecorder] 斗鱼录制不了，前天还能录制，今天就开始报错了，测试了虎牙可以录制但是斗鱼录不了 (Issue #68)





 
image.png (view on web)
 我这边测试能录制啊
