### ISSUE TITLE
录制 Twitcasting 报错过多

### ISSUE THREAD

**Issue by HanekawaHiro** [auqhjjqdo/LiveRecorder#71]
### 运行环境

版本号：v2.22
运行平台：Windows
运行架构：x64
Python版本：LiveRecorder_Windows_v2.22

### 配置文件

```JSON
{
  "proxy": "http://127.0.0.1:1201",
  "output": "output",
  "user": [
    {
      "platform": "Twitcasting",
      "id": "c:miiiiiiii41",
      "name": "miiiiiiii41",
      "interval": 3
    },
    {
      "platform": "Twitcasting",
      "id": "n2_8_",
      "name": "n2_8_",
      "interval": 3
    }
  ]
}
```

### 复现步骤（可选）

1.
2.
3.
...

### 错误描述

个别直播间未开播时重复抛出错误生成巨大log文件

### 错误日志

```Text
2023-12-20 17:28:48.335 | INFO     | __main__:start:46 - [Twitcasting][miiiiiiii41]正在检测直播状态
2023-12-20 17:28:48.343 | INFO     | __main__:start:46 - [Twitcasting][n2_8_]正在检测直播状态
2023-12-20 17:28:49.812 | ERROR    | __main__:start:57 - [Twitcasting][miiiiiiii41]直播检测错误
KeyError('movie')
Traceback (most recent call last):

  File "live_recorder.py", line 428, in <module>

  File "asyncio\runners.py", line 44, in run

  File "asyncio\base_events.py", line 636, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 603, in run_forever

  File "asyncio\base_events.py", line 1909, in _run_once

  File "asyncio\events.py", line 80, in _run

> File "live_recorder.py", line 49, in start

  File "live_recorder.py", line 359, in run

KeyError: 'movie'
2023-12-20 17:28:49.831 | ERROR    | __main__:start:57 - [Twitcasting][n2_8_]直播检测错误
KeyError('movie')
Traceback (most recent call last):

  File "live_recorder.py", line 428, in <module>

  File "asyncio\runners.py", line 44, in run

  File "asyncio\base_events.py", line 636, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 603, in run_forever

  File "asyncio\base_events.py", line 1909, in _run_once

  File "asyncio\events.py", line 80, in _run

> File "live_recorder.py", line 49, in start

  File "live_recorder.py", line 359, in run

KeyError: 'movie'
2023-12-20 17:28:50.178 | ERROR    | __main__:start:57 - [Twitcasting][n2_8_]直播检测错误
KeyError('movie')
Traceback (most recent call last):

  File "live_recorder.py", line 428, in <module>

  File "asyncio\runners.py", line 44, in run

  File "asyncio\base_events.py", line 636, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 603, in run_forever

  File "asyncio\base_events.py", line 1909, in _run_once

  File "asyncio\events.py", line 80, in _run

> File "live_recorder.py", line 49, in start

  File "live_recorder.py", line 359, in run

KeyError: 'movie'
2023-12-20 17:28:50.222 | ERROR    | __main__:start:57 - [Twitcasting][miiiiiiii41]直播检测错误
KeyError('movie')
Traceback (most recent call last):

  File "live_recorder.py", line 428, in <module>

  File "asyncio\runners.py", line 44, in run

  File "asyncio\base_events.py", line 636, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 603, in run_forever

  File "asyncio\base_events.py", line 1909, in _run_once

  File "asyncio\events.py", line 80, in _run

> File "live_recorder.py", line 49, in start

  File "live_recorder.py", line 359, in run

KeyError: 'movie'
2023-12-20 17:28:50.562 | ERROR    | __main__:start:57 - [Twitcasting][n2_8_]直播检测错误
KeyError('movie')
Traceback (most recent call last):

  File "live_recorder.py", line 428, in <module>

  File "asyncio\runners.py", line 44, in run

  File "asyncio\base_events.py", line 636, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 603, in run_forever

  File "asyncio\base_events.py", line 1909, in _run_once

  File "asyncio\events.py", line 80, in _run

> File "live_recorder.py", line 49, in start

  File "live_recorder.py", line 359, in run

KeyError: 'movie'
2023-12-20 17:28:50.608 | ERROR    | __main__:start:57 - [Twitcasting][miiiiiiii41]直播检测错误
KeyError('movie')
Traceback (most recent call last):

  File "live_recorder.py", line 428, in <module>

  File "asyncio\runners.py", line 44, in run

  File "asyncio\base_events.py", line 636, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 603, in run_forever

  File "asyncio\base_events.py", line 1909, in _run_once

  File "asyncio\events.py", line 80, in _run

> File "live_recorder.py", line 49, in start

  File "live_recorder.py", line 359, in run

KeyError: 'movie'
2023-12-20 17:28:50.906 | ERROR    | __main__:start:57 - [Twitcasting][n2_8_]直播检测错误
KeyError('movie')
Traceback (most recent call last):

  File "live_recorder.py", line 428, in <module>

  File "asyncio\runners.py", line 44, in run

  File "asyncio\base_events.py", line 636, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 603, in run_forever

  File "asyncio\base_events.py", line 1909, in _run_once

  File "asyncio\events.py", line 80, in _run

> File "live_recorder.py", line 49, in start

  File "live_recorder.py", line 359, in run

KeyError: 'movie'
2023-12-20 17:28:50.963 | ERROR    | __main__:start:57 - [Twitcasting][miiiiiiii41]直播检测错误
KeyError('movie')
Traceback (most recent call last):

  File "live_recorder.py", line 428, in <module>

  File "asyncio\runners.py", line 44, in run

  File "asyncio\base_events.py", line 636, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 603, in run_forever

  File "asyncio\base_events.py", line 1909, in _run_once

  File "asyncio\events.py", line 80, in _run

> File "live_recorder.py", line 49, in start

  File "live_recorder.py", line 359, in run

KeyError: 'movie'
2023-12-20 17:28:51.248 | ERROR    | __main__:start:57 - [Twitcasting][n2_8_]直播检测错误
KeyError('movie')
Traceback (most recent call last):

  File "live_recorder.py", line 428, in <module>

  File "asyncio\runners.py", line 44, in run

  File "asyncio\base_events.py", line 636, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 603, in run_forever

  File "asyncio\base_events.py", line 1909, in _run_once

  File "asyncio\events.py", line 80, in _run

> File "live_recorder.py", line 49, in start

  File "live_recorder.py", line 359, in run

KeyError: 'movie'
2023-12-20 17:28:51.331 | ERROR    | __main__:start:57 - [Twitcasting][miiiiiiii41]直播检测错误
KeyError('movie')
Traceback (most recent call last):

  File "live_recorder.py", line 428, in <module>

  File "asyncio\runners.py", line 44, in run

  File "asyncio\base_events.py", line 636, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 603, in run_forever

  File "asyncio\base_events.py", line 1909, in _run_once

  File "asyncio\events.py", line 80, in _run

> File "live_recorder.py", line 49, in start

  File "live_recorder.py", line 359, in run

KeyError: 'movie'
2023-12-20 17:28:51.592 | ERROR    | __main__:start:57 - [Twitcasting][n2_8_]直播检测错误
KeyError('movie')
Traceback (most recent call last):

  File "live_recorder.py", line 428, in <module>

  File "asyncio\runners.py", line 44, in run

  File "asyncio\base_events.py", line 636, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 603, in run_forever

  File "asyncio\base_events.py", line 1909, in _run_once

  File "asyncio\events.py", line 80, in _run

> File "live_recorder.py", line 49, in start

  File "live_recorder.py", line 359, in run

KeyError: 'movie'
```

**Comment by auqhjjqdo** [comment]
你两个直播都是twitcasting的直播而且interval设置为3秒，相当于每3秒请求2次，这不被风控就怪了

**Comment by HanekawaHiro** [comment]
> 你两个直播都是twitcasting的直播而且interval设置为3秒，相当于每3秒请求2次，这不被风控就怪了

抱歉，我的描述存在一些不准确之处
实际主播开播时会正常录制
这是开播时的log
[log_2023-12-20.log](https://github.com/auqhjjqdo/LiveRecorder/files/13726473/log_2023-12-20.log)

**Comment by auqhjjqdo** [comment]
看了下在同时存在两个及以上的twitcasting直播时，会因为请求频率过高导致官方服务器风控不返回直播数据，可能需要更换请求的接口

**Comment by auqhjjqdo** [comment]
已修改twitcasting直播检测开播判定，请尝试v2.30是否修复成功
