### ISSUE TITLE
配置文件未修改,抖音录制报错

### ISSUE THREAD

**Issue by xjl456852** [auqhjjqdo/LiveRecorder#77]
### 运行环境

版本号：2.3.0
运行平台：windows
运行架构：
Python版本：

### 配置文件

```JSON
{
  "output": "output",
  "user": [
        {
        "platform": "Douyin",
        "id": "523319717004",
        "name": "juuu"
        },
        {
                "platform": "Douyin",
                "id": "30883172576",
                "name": "hengyuanxiang"
        }
]
}
```

### 错误描述

配置文件未修改,现在无法录制.之前是可以的.应该是抖音官网改了规则了.

### 错误日志

```Text
son.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-12-27 10:54:06.715 | ERROR    | __main__:start:58 - [Douyin][juuu]直播检测错误
JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
Traceback (most recent call last):

  File "live_recorder.py", line 483, in <module>

  File "asyncio\runners.py", line 44, in run

  File "asyncio\base_events.py", line 636, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 603, in run_forever

  File "asyncio\base_events.py", line 1909, in _run_once

  File "asyncio\events.py", line 80, in _run

> File "live_recorder.py", line 50, in start

  File "live_recorder.py", line 272, in run

  File "httpx\_models.py", line 761, in json

  File "json\__init__.py", line 346, in loads

  File "json\decoder.py", line 337, in decode

  File "json\decoder.py", line 355, in raw_decode

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by auqhjjqdo** [comment]
请不要重复发issue
https://github.com/auqhjjqdo/LiveRecorder/issues/76

**Comment by auqhjjqdo** [comment]
v2.31已修复抖音直播录制报错
