### ISSUE TITLE
pandalive填写cookies后会报错

### ISSUE THREAD

**Issue by xueli12** [auqhjjqdo/LiveRecorder#80]
### 运行环境

版本号：2.31
运行平台：windows10
运行架构：windows10
Python版本：Python3.9

### 配置文件

```JSON
{
  "proxy": "http://127.0.0.1:10809",
  "output": "output",
  "user": [
    
    {
      "platform": "Pandalive",
      "id": "sodam0",
      "name": "sodam0"
      "cookies": ""
    }
  ]
}
```

### 复现步骤（可选）

1.
2.
3.
...

### 错误描述

正常情况下不填cookies也可以录制到非登录状态下的直播。但是有些直播需要实名认证登录后才能观看，因此需要填写cookie，但填了cookie后会报错。也有可能我配置文件填的不对？

### 错误日志

```Text
Traceback (most recent call last):
  File "live_recorder.py", line 506, in <module>
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "live_recorder.py", line 482, in run
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 10 column 7 (char 166)
[32012] Failed to execute script 'live_recorder' due to unhandled exception!
```

**Comment by auqhjjqdo** [comment]
cookies格式填写错误没识别出来
