### ISSUE TITLE
bigo检测错误

### ISSUE THREAD

**Issue by Hertz221** [auqhjjqdo/LiveRecorder#89]
### 运行环境

版本号：2.32
运行平台：win11
运行架构：x64
Python版本：

### 配置文件

```JSON
{
      "platform": "Bigolive",
      "id": "859142915",
      "interval": 50,
      "name": "TongTong",
      "format": "mp4"
    }
  ]
}
```

### 复现步骤（可选）

1.
2.
3.
...

### 错误描述

录制中出现的错误，还在播但是没录，重启后正常

### 错误日志

```Text
[2024-02-21 14:30:29][INFO][__main__][stream_writer:153][Bigolive][TongTong]正在录制：[2024.02.21 14.30.28][Bigolive][TongTong]#Chat .ts
[2024-02-21 14:30:29][INFO][__main__][stream_writer:153][Bigolive][Thaothao]正在录制：[2024.02.21 14.30.23][Bigolive][Thaothao]Nhảy múa 💃🏻 dance 💃🏻💃🏻💃🏻.ts
[2024-02-21 14:35:58][INFO][__main__][run_ffmpeg:167][Bigolive][Thaothao]开始ffmpeg封装：[2024.02.21 14.30.23][Bigolive][Thaothao]Nhảy múa 💃🏻 dance 💃🏻💃🏻💃🏻.ts
[2024-02-21 14:35:58][INFO][__main__][run_ffmpeg:167][Bigolive][TongTong]开始ffmpeg封装：[2024.02.21 14.30.28][Bigolive][TongTong]#Chat .ts
[2024-02-21 14:35:59][ERROR][__main__][start:58][Bigolive][Thaothao]直播检测错误
Error('ffmpeg error (see stderr output for detail)')
Traceback (most recent call last):

  File "live_recorder.py", line 507, in <module>

  File "asyncio\runners.py", line 44, in run

  File "asyncio\base_events.py", line 636, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 603, in run_forever

  File "asyncio\base_events.py", line 1909, in _run_once

  File "asyncio\events.py", line 80, in _run

> File "live_recorder.py", line 50, in start

  File "live_recorder.py", line 457, in run

  File "asyncio\threads.py", line 25, in to_thread

  File "concurrent\futures\thread.py", line 58, in run

  File "live_recorder.py", line 140, in run_record

  File "live_recorder.py", line 174, in run_ffmpeg

  File "ffmpeg\_run.py", line 325, in run

ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
[2024-02-21 14:35:59][ERROR][__main__][start:58][Bigolive][TongTong]直播检测错误
Error('ffmpeg error (see stderr output for detail)')
Traceback (most recent call last):

  File "live_recorder.py", line 507, in <module>

  File "asyncio\runners.py", line 44, in run

  File "asyncio\base_events.py", line 636, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 603, in run_forever

  File "asyncio\base_events.py", line 1909, in _run_once

  File "asyncio\events.py", line 80, in _run

> File "live_recorder.py", line 50, in start

  File "live_recorder.py", line 457, in run

  File "asyncio\threads.py", line 25, in to_thread

  File "concurrent\futures\thread.py", line 58, in run

  File "live_recorder.py", line 140, in run_record

  File "live_recorder.py", line 174, in run_ffmpeg

  File "ffmpeg\_run.py", line 325, in run

ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
```

**Comment by auqhjjqdo** [comment]
ffmpeg的问题，请截图运行界面看看ffmpeg报错是什么

**Comment by Hertz221** [comment]
上次直接关了没截图，等下次出现我再截吧

**Comment by Hertz221** [comment]
完整是这样的
<img src="https://img.wnflb2023.com/i/2024/02/24/144150.png" alt="PixPin_2024-02-24_14-40-21" />

**Comment by Hertz221** [comment]
他会把两个主播的视频合成一个！导致花屏，完全看不了

**Comment by auqhjjqdo** [comment]
> 他会把两个主播的视频合成一个！导致花屏，完全看不了

你把format参数删了，不使用封装看看是不是也花屏

**Comment by Hertz221** [comment]
花屏这个问题好像是主播网络问题。但是上面的错误是文件名是1主播，画面是2主播，不加format参数就不会转码大概没啥问题？我现在没加format参数目前好像没啥问题

**Comment by auqhjjqdo** [comment]
加了format参数会运行ffmpeg封装，封装是基于已经录制好的文件转换成format参数指定格式的文件，理论上不可能出现混流成其他主播的情况，可能是bigolive的直播流本身的问题，其他平台就不会出现混流现象，暂时无解
